import { Genres, GenresSelectOption } from './types'

export const enGenresMock: Genres[] = [
  { id: 28, name: 'Action' },
  { id: 12, name: 'Adventure' },
  { id: 16, name: 'Animation' },
  { id: 35, name: 'Comedy' },
  { id: 80, name: 'Crime' },
  { id: 99, name: 'Documentary' },
  { id: 18, name: 'Drama' },
  { id: 10751, name: 'Family' },
  { id: 14, name: 'Fantasy' },
  { id: 36, name: 'History' },
  { id: 27, name: 'Horror' },
  { id: 10402, name: 'Music' },
  { id: 9648, name: 'Mystery' },
  { id: 10749, name: 'Romance' },
  { id: 878, name: 'Science Fiction' },
  { id: 10770, name: 'TV Movie' },
  { id: 53, name: 'Thriller' },
  { id: 10752, name: 'War' },
  { id: 37, name: 'Western' },
]

export const enGenresSelectMock: GenresSelectOption[] = [
  { value: 28, label: 'Action' },
  { value: 12, label: 'Adventure' },
  { value: 16, label: 'Animation' },
  { value: 35, label: 'Comedy' },
  { value: 80, label: 'Crime' },
  { value: 99, label: 'Documentary' },
  { value: 18, label: 'Drama' },
  { value: 10751, label: 'Family' },
  { value: 14, label: 'Fantasy' },
  { value: 36, label: 'History' },
  { value: 27, label: 'Horror' },
  { value: 10402, label: 'Music' },
  { value: 9648, label: 'Mystery' },
  { value: 10749, label: 'Romance' },
  { value: 878, label: 'Science Fiction' },
  { value: 10770, label: 'TV Movie' },
  { value: 53, label: 'Thriller' },
  { value: 10752, label: 'War' },
  { value: 37, label: 'Western' },
]
export const ruGenresMock: Genres[] = [
  { id: 28, name: 'боевик' },
  { id: 12, name: 'приключения' },
  { id: 16, name: 'мультфильм' },
  { id: 35, name: 'комедия' },
  { id: 80, name: 'криминал' },
  { id: 99, name: 'документальный' },
  { id: 18, name: 'драма' },
  { id: 10751, name: 'семейный' },
  { id: 14, name: 'фэнтези' },
  { id: 36, name: 'история' },
  { id: 27, name: 'ужасы' },
  { id: 10402, name: 'музыка' },
  { id: 9648, name: 'детектив' },
  { id: 10749, name: 'мелодрама' },
  { id: 878, name: 'фантастика' },
  { id: 10770, name: 'телевизионный фильм' },
  { id: 53, name: 'триллер' },
  { id: 10752, name: 'военный' },
  { id: 37, name: 'вестерн' },
]

export const emptyGenre: GenresSelectOption = { value: '', label: 'Any genre' }

export const ruGenresSelectMock: GenresSelectOption[] = [
  { value: 28, label: 'Боевик' },
  { value: 12, label: 'Приключения' },
  { value: 16, label: 'Мультфильм' },
  { value: 35, label: 'Комедия' },
  { value: 80, label: 'Криминал' },
  { value: 99, label: 'Документальный' },
  { value: 18, label: 'Драма' },
  { value: 10751, label: 'Семейный' },
  { value: 14, label: 'Фэнтези' },
  { value: 36, label: 'История' },
  { value: 27, label: 'Ужасы' },
  { value: 10402, label: 'Музыка' },
  { value: 9648, label: 'Детектив' },
  { value: 10749, label: 'Мелодрама' },
  { value: 878, label: 'Фантастика' },
  { value: 10770, label: 'Телевизионный фильм' },
  { value: 53, label: 'Триллер' },
  { value: 10752, label: 'Военный' },
  { value: 37, label: 'Вестерн' },
]
